name: NPM Unpublish
on:
  release:
    types: [ deleted ]
jobs:
  unpublish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    permissions:
      contents: read
      id-token: write
    steps:
      # cannot checkout the release that got deleted since the associated tag does not exist anymore
      # checking out code is required for the npm unpublish command to work.
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Unpublish from NPM
        run: npm unpublish @smals-belgium/myhealth-wc-integration@${GITHUB_REF_NAME:1}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
